name: android_automotive_plugin_example
description: "Demonstrates how to use the android_automotive_plugin plugin."
publish_to: "none"

environment:
  sdk: "^3.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Это ключевое изменение - мы говорим, что плагин лежит в папке выше
  android_automotive_plugin:
    path: ../

  flutter_background_service: ^5.0.5
  permission_handler: ^11.3.1
  flutter_mobx: ^2.2.1
  mobx: ^2.3.3+2
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  mobx_codegen: ^2.6.1
  flutter_lints: ^3.0.0
